// 大模型API数据
// 最后更新时间：2026-04-10
// 价格单位：美元/千Token

const MODELS_DATA = {
    version: "1.0.0",
    lastUpdate: "2026-04-10",
    source: "各厂商官方文档",
    models: [
        // ========== 顶级旗舰模型 ==========
        {
            id: "claude-opus-4-6",
            name: "Claude Opus 4.6",
            provider: "Anthropic",
            providerKey: "anthropic",
            providerLogo: "🔬",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 5.00,
            outputPrice: 25.00,
            contextWindow: "1M (Beta)",
            features: ["代码能力最强", "SWE-bench 80.8%", "128K最大输出", "安全对齐"],
            specialties: "编程能力业界最强，在软件工程基准测试中创下SOTA成绩，深度推理能力出众",
            badges: ["new"],
            category: ["tier1", "multimodal"],
            url: "https://www.anthropic.com/api"
        },
        {
            id: "gemini-3-1-pro",
            name: "Gemini 3.1 Pro",
            provider: "Google",
            providerKey: "google",
            providerLogo: "🔵",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 2.00,
            outputPrice: 12.00,
            contextWindow: "1M",
            features: ["ARC-AGI-2 77.1%", "原生视频理解", "长上下文", "多模态"],
            specialties: "ARC-AGI-2得分77.1%，原生支持视频理解，超长上下文处理能力",
            badges: ["new"],
            category: ["tier1", "multimodal"],
            url: "https://ai.google.dev"
        },
        {
            id: "gpt-5",
            name: "GPT-5",
            provider: "OpenAI",
            providerKey: "openai",
            providerLogo: "🧠",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 1.25,
            outputPrice: 10.00,
            contextWindow: "400K",
            features: ["综合能力均衡", "多模态", "Function Calling", "GPTs生态"],
            specialties: "综合能力最强，多模态原生支持，拥有最成熟的生态系统和工具链",
            badges: ["hot"],
            category: ["tier1", "multimodal"],
            url: "https://platform.openai.com"
        },
        {
            id: "claude-opus-4-5",
            name: "Claude Opus 4.5",
            provider: "Anthropic",
            providerKey: "anthropic",
            providerLogo: "🔬",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 5.00,
            outputPrice: 25.00,
            contextWindow: "200K",
            features: ["极致推理", "复杂分析", "长文档处理", "代码生成"],
            specialties: "极致推理能力，适合复杂分析任务和长文档深度理解",
            badges: [],
            category: ["tier1"],
            url: "https://www.anthropic.com/api"
        },
        {
            id: "gemini-2-5-pro",
            name: "Gemini 2.5 Pro",
            provider: "Google",
            providerKey: "google",
            providerLogo: "🔵",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 1.25,
            outputPrice: 10.00,
            contextWindow: "1M",
            features: ["超长上下文", "多模态", "代码生成", "推理能力"],
            specialties: "百万级上下文窗口，超长文本处理能力，多模态综合能力出色",
            badges: [],
            category: ["tier1", "multimodal"],
            url: "https://ai.google.dev"
        },
        {
            id: "grok-3",
            name: "Grok 3",
            provider: "xAI",
            providerKey: "xai",
            providerLogo: "⚡",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 3.00,
            outputPrice: 15.00,
            contextWindow: "128K",
            features: ["强推理能力", "实时信息", "幽默风格", "X平台整合"],
            specialties: "强推理能力，实时获取X平台信息，回复风格独特",
            badges: [],
            category: ["tier1"],
            url: "https://x.ai/api"
        },
        {
            id: "o3",
            name: "o3",
            provider: "OpenAI",
            providerKey: "openai",
            providerLogo: "🧠",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 2.00,
            outputPrice: 8.00,
            contextWindow: "200K",
            features: ["专注推理", "ARC-AGI高分", "复杂问题解决", "STEM能力强"],
            specialties: "专注推理任务，ARC-AGI基准测试高分，复杂数学和科学问题解决能力强",
            badges: ["hot"],
            category: ["tier1", "reasoning"],
            url: "https://platform.openai.com"
        },

        // ========== 性价比模型 ==========
        {
            id: "claude-sonnet-4-6",
            name: "Claude Sonnet 4.6",
            provider: "Anthropic",
            providerKey: "anthropic",
            providerLogo: "🔬",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 3.00,
            outputPrice: 15.00,
            contextWindow: "1M (Beta)",
            features: ["最佳性价比", "SWE-bench 79.6%", "代码能力", "快速响应"],
            specialties: "新一代性价比旗舰，编程能力接近Opus水平，价格更具竞争力",
            badges: ["new"],
            category: ["tier2"],
            url: "https://www.anthropic.com/api"
        },
        {
            id: "gpt-5-3-codex",
            name: "GPT-5.3 Codex",
            provider: "OpenAI",
            providerKey: "openai",
            providerLogo: "🧠",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 2.00,
            outputPrice: 10.00,
            contextWindow: "200K",
            features: ["Agent编程专用", "速度快25%", "32K最大输出", "代码优化"],
            specialties: "专为AI Agent编程设计，比GPT-5.2快25%，代码生成和优化能力增强",
            badges: ["new"],
            category: ["tier2"],
            url: "https://platform.openai.com"
        },
        {
            id: "claude-sonnet-4-5",
            name: "Claude Sonnet 4.5",
            provider: "Anthropic",
            providerKey: "anthropic",
            providerLogo: "🔬",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 3.00,
            outputPrice: 15.00,
            contextWindow: "200K",
            features: ["高质量通用", "平衡性能", "创意写作", "分析推理"],
            specialties: "高质量通用模型，在性能和成本间取得良好平衡",
            badges: [],
            category: ["tier2"],
            url: "https://www.anthropic.com/api"
        },
        {
            id: "gpt-4-1",
            name: "GPT-4.1",
            provider: "OpenAI",
            providerKey: "openai",
            providerLogo: "🧠",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 2.00,
            outputPrice: 8.00,
            contextWindow: "1M",
            features: ["百万上下文", "指令遵循", "长文本处理", "多语言"],
            specialties: "百万级上下文窗口，支持超长文档处理，指令遵循能力强",
            badges: [],
            category: ["tier2"],
            url: "https://platform.openai.com"
        },
        {
            id: "gpt-4o",
            name: "GPT-4o",
            provider: "OpenAI",
            providerKey: "openai",
            providerLogo: "🧠",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 2.50,
            outputPrice: 10.00,
            contextWindow: "128K",
            features: ["多模态", "实时对话", "语音识别", "图像理解"],
            specialties: "原生多模态支持，实时语音对话能力，响应速度快",
            badges: [],
            category: ["tier2", "multimodal"],
            url: "https://platform.openai.com"
        },
        {
            id: "o4-mini",
            name: "o4-mini",
            provider: "OpenAI",
            providerKey: "openai",
            providerLogo: "🧠",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 1.10,
            outputPrice: 4.40,
            contextWindow: "200K",
            features: ["轻量推理", "快速响应", "成本优化", "STEM能力"],
            specialties: "轻量级推理模型，响应快速，成本效益高",
            badges: [],
            category: ["tier2", "reasoning"],
            url: "https://platform.openai.com"
        },
        {
            id: "deepseek-r1",
            name: "DeepSeek R1",
            provider: "DeepSeek",
            providerKey: "deepseek",
            providerLogo: "🔵",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 0.55,
            outputPrice: 2.19,
            contextWindow: "128K",
            features: ["推理场景价格之王", "开源", "长思维链", "数学能力强"],
            specialties: "推理场景性价比之王，开源模型，长思维链推理能力",
            badges: ["hot"],
            category: ["tier2", "reasoning", "opensource", "china"],
            url: "https://platform.deepseek.com"
        },

        // ========== 经济实惠模型 ==========
        {
            id: "deepseek-v3-2",
            name: "DeepSeek V3.2",
            provider: "DeepSeek",
            providerKey: "deepseek",
            providerLogo: "🔵",
            tier: "tier3",
            tierLabel: "经济实惠",
            inputPrice: 0.27,
            outputPrice: 1.10,
            contextWindow: "128K",
            features: ["中文性价比极高", "开源", "代码能力强", "快速生成"],
            specialties: "中文场景性价比极高，开源可商用，代码生成能力出色",
            badges: ["new", "hot"],
            category: ["tier3", "opensource", "china"],
            url: "https://platform.deepseek.com"
        },
        {
            id: "llama-3-3-70b",
            name: "Llama 3.3 70B",
            provider: "Meta",
            providerKey: "meta",
            providerLogo: "🐂",
            tier: "tier3",
            tierLabel: "经济实惠",
            inputPrice: 0.88,
            outputPrice: 0.88,
            contextWindow: "128K",
            features: ["开源", "开源最强者", "指令遵循", "多语言"],
            specialties: "开源Llama系列最强模型，输入输出同价，适合高吞吐场景",
            badges: ["opensource"],
            category: ["tier3", "opensource"],
            url: "https://ai.meta.com"
        },
        {
            id: "gemini-2-5-flash",
            name: "Gemini 2.5 Flash",
            provider: "Google",
            providerKey: "google",
            providerLogo: "🔵",
            tier: "tier3",
            tierLabel: "经济实惠",
            inputPrice: 0.15,
            outputPrice: 0.60,
            contextWindow: "1M",
            features: ["高速处理", "百万上下文", "批量任务", "极速响应"],
            specialties: "高速处理能力，百万上下文窗口，性价比极高的大吞吐模型",
            badges: ["hot"],
            category: ["tier3"],
            url: "https://ai.google.dev"
        },
        {
            id: "gpt-4-1-nano",
            name: "GPT-4.1 Nano",
            provider: "OpenAI",
            providerKey: "openai",
            providerLogo: "🧠",
            tier: "tier3",
            tierLabel: "经济实惠",
            inputPrice: 0.10,
            outputPrice: 0.40,
            contextWindow: "1M",
            features: ["最低价GPT", "百万上下文", "快速响应", "分类提取"],
            specialties: "最低价GPT模型，百万级上下文，适合简单任务大批量处理",
            badges: [],
            category: ["tier3"],
            url: "https://platform.openai.com"
        },
        {
            id: "mistral-small-3-1",
            name: "Mistral Small 3.1",
            provider: "Mistral",
            providerKey: "mistral",
            providerLogo: "🌬️",
            tier: "tier3",
            tierLabel: "经济实惠",
            inputPrice: 0.20,
            outputPrice: 0.60,
            contextWindow: "128K",
            features: ["欧洲合规", "便宜好用", "多语言", "代码能力"],
            specialties: "欧洲合规认证，价格实惠，多语言支持好，代码能力不错",
            badges: [],
            category: ["tier3"],
            url: "https://mistral.ai"
        },
        {
            id: "claude-haiku-4-5",
            name: "Claude Haiku 4.5",
            provider: "Anthropic",
            providerKey: "anthropic",
            providerLogo: "🔬",
            tier: "tier3",
            tierLabel: "经济实惠",
            inputPrice: 1.00,
            outputPrice: 5.00,
            contextWindow: "200K",
            features: ["轻量Claude", "快速响应", "成本控制", "基础能力"],
            specialties: "轻量级Claude模型，响应快速，适合对成本敏感的场景",
            badges: [],
            category: ["tier3"],
            url: "https://www.anthropic.com/api"
        },

        // ========== 国产模型 ==========
        {
            id: "glm-4-flash",
            name: "GLM-4-Flash",
            provider: "智谱AI",
            providerKey: "zhipuai",
            providerLogo: "✨",
            tier: "tier3",
            tierLabel: "免费使用",
            inputPrice: 0,
            outputPrice: 0,
            contextWindow: "128K",
            features: ["完全免费", "永久有效", "代码生成", "中文优化"],
            specialties: "永久免费无Token限制（30并发），代码生成能力国内第一梯队，长期稳定兜底首选",
            badges: ["free", "hot"],
            category: ["tier3", "free", "china"],
            url: "https://open.bigmodel.cn"
        },
        {
            id: "glm-z1-flash",
            name: "GLM-Z1-Flash",
            provider: "智谱AI",
            providerKey: "zhipuai",
            providerLogo: "✨",
            tier: "tier3",
            tierLabel: "免费使用",
            inputPrice: 0,
            outputPrice: 0,
            contextWindow: "128K",
            features: ["永久免费", "推理能力", "快速响应", "中文优化"],
            specialties: "智谱永久免费系列模型，推理能力增强版本",
            badges: ["free", "new"],
            category: ["tier3", "free", "china"],
            url: "https://open.bigmodel.cn"
        },
        {
            id: "kimi-256k",
            name: "Kimi 256K",
            provider: "月之暗面",
            providerKey: "moonshot",
            providerLogo: "🌙",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 0.5,
            outputPrice: 1.5,
            contextWindow: "256K",
            features: ["超长上下文256K", "免费额度", "长文本处理", "文档摘要"],
            specialties: "256K超长上下文，免费额度充足，适合长文档处理和书籍级内容",
            badges: ["free"],
            category: ["tier2", "free", "china"],
            url: "https://platform.moonshot.cn"
        },
        {
            id: "qwen3-series",
            name: "Qwen3 系列",
            provider: "阿里云",
            providerKey: "aliyun",
            providerLogo: "🐧",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 0.5,
            outputPrice: 1.5,
            contextWindow: "128K",
            features: ["开源可商用", "多尺寸", "代码能力强", "中文优化"],
            specialties: "阿里通义千问开源系列，多尺寸可选，代码能力强，中文优化好",
            badges: ["opensource", "hot"],
            category: ["tier2", "opensource", "china"],
            url: "https://bailian.console.aliyun.com"
        },
        {
            id: "wenxin-4-0",
            name: "文心一言 4.0",
            provider: "百度",
            providerKey: "baidu",
            providerLogo: "🔴",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 0.8,
            outputPrice: 2.0,
            contextWindow: "128K",
            features: ["数理逻辑强", "行业覆盖广", "企业级", "中文理解"],
            specialties: "数理逻辑准确率92%+，百度深耕多年的企业级AI能力",
            badges: [],
            category: ["tier2", "china"],
            url: "https://cloud.baidu.com"
        },
        {
            id: "hunyuan-pro",
            name: "混元 Pro",
            provider: "腾讯",
            providerKey: "tencent",
            providerLogo: "🐧",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 0.6,
            outputPrice: 1.8,
            contextWindow: "128K",
            features: ["数学能力强", "腾讯生态", "多模态", "实时交互"],
            specialties: "数学方向排名靠前，与微信、企业微信等腾讯生态深度整合",
            badges: [],
            category: ["tier2", "multimodal", "china"],
            url: "https://cloud.tencent.com"
        },
        {
            id: "doubao-pro",
            name: "豆包 Pro",
            provider: "字节跳动",
            providerKey: "bytedance",
            providerLogo: "🎵",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 0.3,
            outputPrice: 0.9,
            contextWindow: "128K",
            features: ["推理单价极低", "多模态", "字节生态", "高并发"],
            specialties: "推理单价极低，性价比之王，多模态能力完善，字节生态加持",
            badges: ["hot"],
            category: ["tier2", "multimodal", "china"],
            url: "https:// volcengine.volcengine.com"
        },
        {
            id: "spark-4-0",
            name: "星火大模型 4.0",
            provider: "讯飞",
            providerKey: "iflytek",
            providerLogo: "🌟",
            tier: "tier2",
            tierLabel: "性价比",
            inputPrice: 0.5,
            outputPrice: 1.5,
            contextWindow: "128K",
            features: ["语音交互强", "AI绘图", "联网搜索", "长文档"],
            specialties: "语音交互能力强，AI绘图+联网搜索+长文档一体化，综合应用能力强",
            badges: [],
            category: ["tier2", "multimodal", "china"],
            url: "https://xinghuo.xfyun.cn"
        },
        {
            id: "internvl3-78b",
            name: "InternVL3-78B",
            provider: "上海AI Lab",
            providerKey: "intern",
            providerLogo: "📚",
            tier: "tier1",
            tierLabel: "顶级旗舰",
            inputPrice: 0,
            outputPrice: 0,
            contextWindow: "128K",
            features: ["免费API", "10 RPM限制", "视觉能力强", "开源"],
            specialties: "书生·浦语开源系列，视觉理解能力极强，免费API（10 RPM，密钥6个月有效）",
            badges: ["free", "opensource"],
            category: ["tier1", "free", "opensource", "multimodal", "china"],
            url: "https://intern-ai.org.cn"
        },

        // ========== 聚合平台免费模型 ==========
        {
            id: "siliconflow-r1",
            name: "DeepSeek-R1 (硅基流动)",
            provider: "硅基流动",
            providerKey: "deepseek",
            providerLogo: "⚡",
            tier: "tier3",
            tierLabel: "免费使用",
            inputPrice: 0,
            outputPrice: 0,
            contextWindow: "128K",
            features: ["免费API", "1000 RPM", "深度推理", "聚合平台"],
            specialties: "聚合平台免费调用DeepSeek-R1，1000 RPM高频调用限制，开源模型统一接口",
            badges: ["free"],
            category: ["tier3", "free", "reasoning", "china"],
            url: "https://siliconflow.cn"
        },
        {
            id: "modelscope-r1",
            name: "DeepSeek-R1深度推理 (魔搭)",
            provider: "ModelScope魔搭",
            providerKey: "aliyun",
            providerLogo: "🐧",
            tier: "tier3",
            tierLabel: "免费使用",
            inputPrice: 0,
            outputPrice: 0,
            contextWindow: "128K",
            features: ["免费API", "每天200次", "深度推理", "阿里达摩院"],
            specialties: "阿里达摩院ModelScope魔搭社区免费API，深度推理版，每天200次调用",
            badges: ["free"],
            category: ["tier3", "free", "reasoning", "china"],
            url: "https://modelscope.cn"
        },
        {
            id: "modelscope-image",
            name: "Flux.1/QWen-Image (魔搭)",
            provider: "ModelScope魔搭",
            providerKey: "aliyun",
            providerLogo: "🐧",
            tier: "tier3",
            tierLabel: "免费使用",
            inputPrice: 0,
            outputPrice: 0,
            contextWindow: "-",
            features: ["免费API", "每天2000次", "图像生成", "多模态"],
            specialties: "阿里达摩院免费图像生成API，Flux.1文生图+QWen图文多模态，每天2000次调用",
            badges: ["free"],
            category: ["tier3", "free", "multimodal", "china"],
            url: "https://modelscope.cn"
        }
    ]
};

// 导出供外部使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = MODELS_DATA;
}
